// <auto-generated />
namespace Palaver2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EFUpgrade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EFUpgrade));
        
        string IMigrationMetadata.Id
        {
            get { return "201601222211545_EFUpgrade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
